switch to port 8000

diff --git a/license_manager/templates/license_manager/tasks/mysql/init b/license_manager/templates/license_manager/tasks/mysql/init
--- a/license_manager/templates/license_manager/tasks/mysql/init
+++ b/license_manager/templates/license_manager/tasks/mysql/init
@@ -1,3 +1,31 @@
+#!/bin/bash
+#---------------------------------------------------------
+# written by: Lawrence McDaniel
+#             https://lawrencemcdaniel.com
+#
+# date:       aug-2022
+#
+# usage:      create mysql database and user account
+#--------------------------------------------------------
+
+echo "Initialising MySQL..."
+mysql_connection_max_attempts=10
+mysql_connection_attempt=0
+until mysql -u {{ MYSQL_ROOT_USERNAME }} --password="{{ MYSQL_ROOT_PASSWORD }}" --host "{{ MYSQL_HOST }}" --port {{ MYSQL_PORT }} -e 'exit'
+do
+    mysql_connection_attempt=$(expr $mysql_connection_attempt + 1)
+    echo "    [$mysql_connection_attempt/$mysql_connection_max_attempts] Waiting for MySQL service (this may take a while)..."
+    if [ $mysql_connection_attempt -eq $mysql_connection_max_attempts ]
+    then
+      echo "MySQL initialisation error" 1>&2
+      exit 1
+    fi
+    sleep 10
+done
+echo "MySQL is up and running"
+
+
+
 # create the license manager database
 echo "create license_manager database"
 mysql -u {{ MYSQL_ROOT_USERNAME }} --password="{{ MYSQL_ROOT_PASSWORD }}" --host "{{ MYSQL_HOST }}" --port {{ MYSQL_PORT }} -e "CREATE DATABASE IF NOT EXISTS {{ LICENSE_MANAGER_MYSQL_DATABASE }};"
